version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: field_hockey_broadcast
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d field_hockey_broadcast"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./platform/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/field_hockey_broadcast
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key-change-in-production # Change this in production
      ALLOWED_ORIGINS: '["http://localhost:3000", "http://localhost:8080", "http://127.0.0.1:3000", "http://127.0.0.1:8080"]'
      ALLOWED_HOSTS: '["localhost", "127.0.0.1"]'
      PYTHONPATH: /app/backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["/bin/bash", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]

  frontend:
    build:
      context: ./platform/frontend/web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000

volumes:
  postgres_data:
