version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: platform/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./platform/backend:/app
    environment:
      - PYTHONPATH=/app
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: platform/backend/Dockerfile
    command: celery -A cv_models.tasks.celery_app worker --loglevel=info
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./platform/backend:/app
      - ./data:/app/data
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./platform/frontend/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./platform/frontend/web:/app
      - /app/node_modules

volumes:
  postgres_data:
